name: Setup X-UI Panel Automatically

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get Public IP Address
      - name: Get Public IP Address
        id: ip
        run: |
          echo "Getting runner's public IP address..."
          RUNNER_IP=$(curl -s http://checkip.amazonaws.com)
          echo "Public IP is $RUNNER_IP"
          echo "PUBLIC_IP=$RUNNER_IP" >> $GITHUB_ENV

      # Step 3: Install Dependencies (curl and wget)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      # Step 4: Install X-UI Panel with sudo (root privileges)
      - name: Install X-UI Panel
        run: |
          echo "Installing X-UI Panel..."
          sudo curl -Ls https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh | sudo bash
          echo "X-UI installation complete."

      # Step 5: Verify X-UI Installation and Find Config File Location
      - name: Verify X-UI Installation and Locate Config File
        run: |
          echo "Checking installation status..."
          # Check the X-UI service status
          sudo systemctl status x-ui
          # Check if the configuration file exists
          CONFIG_FILE=$(sudo find / -name "x-ui.conf" | head -n 1)
          if [ -z "$CONFIG_FILE" ]; then
            echo "Configuration file not found. Attempting to locate the file..."
            sudo find / -name "x-ui.conf"
            exit 1
          fi
          echo "X-UI configuration file located at: $CONFIG_FILE"
        
      # Step 6: Update X-UI Configuration with Public IP (if the file is found)
      - name: Update X-UI Configuration
        run: |
          if [ -z "$CONFIG_FILE" ]; then
            echo "X-UI configuration file not found. Cannot proceed with configuration."
            exit 1
          fi
          echo "Updating X-UI configuration to bind to public IP..."
          sudo sed -i "s/127.0.0.1/$PUBLIC_IP/" "$CONFIG_FILE"
          echo "X-UI configuration updated."

      # Step 7: Configure X-UI with Username and Password
      - name: Configure X-UI with Username and Password
        run: |
          echo "Configuring X-UI Panel..."
          sudo x-ui setuser "${{ secrets.XUI_USERNAME }}" "${{ secrets.XUI_PASSWORD }}"

      # Step 8: Start the X-UI Service
      - name: Start X-UI Service
        run: |
          echo "Starting X-UI service..."
          sudo systemctl start x-ui
          sudo systemctl enable x-ui

      # Step 9: Output X-UI Panel Access URL
      - name: Output Panel Access Information
        run: |
          echo "X-UI Panel is successfully installed and running."
          echo "You can access the panel at: http://$PUBLIC_IP:54321"
