name: Setup X-UI Panel

on:
  push:
    branches:
      - main

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install necessary dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl

    - name: Download and Configure X-UI Panel
      run: |
        wget https://github.com/NidukaAkalanka/x-ui-english/raw/main/x-ui.sh
        chmod +x x-ui.sh
        ./x-ui.sh install

    - name: Set up the configuration (without root)
      run: |
        echo "Setting up X-UI config"
        CONFIG_FILE=$(sudo find / -name "x-ui.conf" | head -n 1)
        echo "Config file found at: $CONFIG_FILE"
        sudo sed -i 's/0.0.0.0/$(curl -s ifconfig.me)/' $CONFIG_FILE
        sudo systemctl restart x-ui

    - name: Output the X-UI URL
      run: |
        echo "The X-UI Panel should now be accessible at http://$(curl -s ifconfig.me):54321"
