name: X-UI Panel Setup with Auto IP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install required dependencies
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip

    # Step 3: Get public IP address of the runner
    - name: Fetch public IP address
      id: ip_address
      run: |
        IP=$(curl -s https://api.ipify.org)
        echo "Public IP: $IP"
        echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

    # Step 4: Download and install X-UI (assuming it's now a .zip file)
    - name: Install X-UI Panel
      run: |
        curl -sSL https://github.com/vaxilu/x-ui/releases/download/v1.0.0/x-ui-linux-amd64.zip -o x-ui.zip
        unzip x-ui.zip
        cd x-ui
        chmod +x x-ui
        sudo mv x-ui /usr/local/bin/

    # Step 5: Configure X-UI Panel with the fetched IP address
    - name: Configure X-UI Panel
      run: |
        # Use the dynamically fetched IP address (stored in the PUBLIC_IP environment variable)
        echo "Configuring X-UI with IP: $PUBLIC_IP"
        curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "new_user", "password": "secure_password", "ip": "'$PUBLIC_IP'"}' \
          http://localhost:9999/api/create_user

    # Step 6: Run the X-UI panel (adjust command based on X-UI setup)
    - name: Start X-UI Panel
      run: |
        nohup /usr/local/bin/x-ui start &
        sleep 5 # Wait a bit for the server to start

    # Step 7: Check the panel status (optional, just for verification)
    - name: Check X-UI Panel Status
      run: |
        curl http://localhost:9999/status
        # or use any other command to verify if X-UI is running
