name: Prepare X-UI Setup

on:
  push:
    branches:
      - main

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install necessary dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl

    - name: Download X-UI installation script
      run: |
        wget https://raw.githubusercontent.com/NidukaAkalanka/x-ui-english/main/x-ui.sh
        chmod +x x-ui.sh

    - name: Prepare configuration (without root access)
      run: |
        echo "Preparing X-UI config"
        CONFIG_FILE=$(find / -name "x-ui.conf" | head -n 1)
        echo "Config file found at: $CONFIG_FILE"
        echo "The X-UI panel should be set up on your server. Please run it with root privileges."
        
    - name: Output instructions for server
      run: |
        echo "Follow the instructions below to finish installation on your server:"
        echo "1. Upload x-ui.sh and run it on your server with root access."
        echo "2. Set the correct public IP in the configuration file."
        echo "3. Access the panel at http://<your-server-ip>:54321"
