name: X-UI Panel Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-x-ui:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up environment - Install necessary packages
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl wget sudo ufw

    # Step 3: Download and configure X-UI
    - name: Download X-UI installation script
      run: |
        wget https://github.com/NidukaAkalanka/x-ui-english/raw/main/x-ui.sh -O x-ui.sh
        chmod +x x-ui.sh

    # Step 4: Install X-UI panel
    - name: Install X-UI Panel
      run: |
        echo "Starting X-UI installation..."
        sudo ./x-ui.sh install

    # Step 5: Start X-UI Panel service
    - name: Start X-UI service
      run: |
        echo "Starting X-UI service..."
        sudo systemctl start x-ui
        sudo systemctl enable x-ui

    # Step 6: Check if X-UI is running
    - name: Check X-UI status
      run: |
        echo "Checking X-UI service status..."
        sudo systemctl status x-ui | head -n 10

    # Step 7: Open firewall for X-UI port
    - name: Open firewall port for X-UI
      run: |
        echo "Opening firewall port for X-UI..."
        sudo ufw allow 54321/tcp
        sudo ufw enable

    # Step 8: Output public IP and Panel URL
    - name: Output Panel URL
      run: |
        echo "X-UI Panel is running!"
        echo "Panel URL: http://$(curl -s ifconfig.me):54321"
        echo "Login credentials: "
        echo "Username: $(openssl rand -base64 12)"
        echo "Password: $(openssl rand -base64 16)"

    # Step 9: Optional - Restart panel in case of any failure
    - name: Restart X-UI if necessary
      run: |
        echo "Checking for any issues and restarting if necessary..."
        sudo systemctl restart x-ui
