name: Install X-UI Panel

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  install-x-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install X-UI Panel
        run: |
          echo "Running X-UI installation script as root..."
          sudo bash <(curl -Ls https://raw.githubusercontent.com/NidukaAkalanka/x-ui-english/master/install.sh)

      - name: Wait for X-UI installation to complete
        run: sleep 30 # Adjust as necessary for installation to complete

      - name: Check X-UI Service Status
        run: |
          echo "Checking the status of X-UI..."
          sudo systemctl status x-ui.service
          
      - name: Display Access Information
        run: |
          # Show the public IP and other X-UI access details
          echo "Fetching X-UI access details..."
          PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
          echo "X-UI Panel can be accessed at: http://$PUBLIC_IP:54321"
          echo "Username: your_username"  # Replace with the actual username
          echo "Password: your_password"  # Replace with the actual password
