name: Deploy X-UI Panel

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install dependencies on the server
        run: |
          ssh -i ~/.ssh/id_rsa username@${{ secrets.SERVER_IP }} << 'EOF'
            sudo apt-get update && sudo apt-get install -y wget curl unzip
          EOF

      - name: Download and Install X-UI
        run: |
          ssh -i ~/.ssh/id_rsa username@${{ secrets.SERVER_IP }} << 'EOF'
            wget https://github.com/NidukaAkalanka/x-ui-english/raw/main/x-ui.sh -O /tmp/x-ui.sh
            bash /tmp/x-ui.sh
          EOF

      - name: Configure X-UI Panel
        run: |
          ssh -i ~/.ssh/id_rsa username@${{ secrets.SERVER_IP }} << 'EOF'
            CONFIG_FILE=$(sudo find / -name "x-ui.conf" | head -n 1)
            sed -i "s/127.0.0.1/0.0.0.0/" $CONFIG_FILE  # Bind X-UI to public IP
            sudo systemctl restart x-ui
          EOF

      - name: Get Public IP of the server
        id: get_ip
        run: |
          echo "::set-output name=public_ip::$(curl -s http://ifconfig.me)"

      - name: Display X-UI Panel URL
        run: |
          echo "X-UI Panel is accessible at: http://${{ steps.get_ip.outputs.public_ip }}:54321"
