name: X-UI Panel Setup

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  setup-panel:
    runs-on: ubuntu-latest # Use a Linux environment
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Install dependencies
      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      # Step 3: Install x-ui panel
      - name: Install X-UI Panel
        run: |
          bash <(curl -Ls https://raw.githubusercontent.com/vaxilu/x-ui/master/install.sh)
      
      # Step 4: Start the x-ui service
      - name: Start X-UI Service
        run: |
          systemctl start x-ui
          systemctl enable x-ui
      
      # Step 5: Show completion message
      - name: Complete Setup
        run: echo "X-UI Panel setup is complete!"
