name: Set up X-UI Panel

on:
  push:
    branches:
      - main

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install wget and curl
      run: |
        sudo apt update
        sudo apt install -y wget curl

    - name: Download X-UI Installation Script
      run: |
        wget https://raw.githubusercontent.com/NidukaAkalanka/x-ui-english/main/x-ui.sh
        chmod +x x-ui.sh

    - name: Generate Public IP and Panel URL
      run: |
        # This will simulate fetching the public IP for the real server setup
        PUBLIC_IP=$(curl -s ifconfig.me)  # Will work on a real server, simulate here
        echo "Public IP of the server: $PUBLIC_IP"
        
        # Generate the X-UI panel URL
        URL="http://$PUBLIC_IP:54321"
        echo "X-UI panel URL: $URL"

    - name: Display Instructions
      run: |
        echo "Follow these instructions to complete your X-UI setup:"
        echo "1. Upload x-ui.sh to your server and execute it with root privileges."
        echo "2. Once the server is up, use the URL below to access the X-UI panel:"
        echo "   $URL"
