name: X-UI Panel Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-xui:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install dependencies
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip

    # Step 3: Download and install X-UI (assuming it's Xray or V2Ray based)
    - name: Install X-UI Panel
      run: |
        curl -sSL https://github.com/vaxilu/x-ui/releases/download/v1.0.0/x-ui-linux-amd64.tar.gz -o x-ui.tar.gz
        tar -xzf x-ui.tar.gz
        cd x-ui
        chmod +x x-ui
        sudo mv x-ui /usr/local/bin/

    # Step 4: Setup and configure the X-UI
    - name: Configure X-UI Panel
      run: |
        # Set up necessary configurations here
        # Example: Create a new user profile for X-UI
        curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "new_user", "password": "secure_password"}' \
          http://localhost:9999/api/create_user

    # Step 5: Run the X-UI panel (adjust command based on X-UI setup)
    - name: Start X-UI Panel
      run: |
        nohup /usr/local/bin/x-ui start &
        sleep 5 # Wait a bit for the server to start

    # Step 6: Check the panel status (optional, just for verification)
    - name: Check X-UI Panel Status
      run: |
        curl http://localhost:9999/status
        # or use any other command to verify if X-UI is running
